name: Deploy

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: print info
        env:
          $INFO1: ${{toJson(github)}}
        run: echo "$INFO1"
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "calm-lowlands-44218"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://calm-lowlands-44218.herokuapp.com/health"
          rollbackonhealthcheckfailed: true

