name: Deploy

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' && ! contains(join(github.event.commits.*.message),'#skip')}}  
    runs-on: ubuntu-18.04
    steps:
      - name: print github
        env:
          INFO: ${{ toJson(github)}}
        run: echo "$INFO"     
      - name: print info3
        env:
          INFO3: ${{ toJson(github.event.commits.*.message)}}
        run: echo "$INFO3"    
      - name: print info1
        env:
          INFO1: ${{ toJson(join(github.event.commits.*.message))}}
        run: echo "$INFO1"
      - name: print info2
        env:
          INFO2: ${{ toJson(!contains(join(github.event.commits.*.message),'#skip'))}}
        run: echo "$INFO2"        
      - name: print info
        env:
          INFO: ${{ toJson(! contains(join(github.event.commits.*.message),'#skip'))}}
        run: echo "$INFO"
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "calm-lowlands-44218"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://calm-lowlands-44218.herokuapp.com/health"
          rollbackonhealthcheckfailed: true

