name: Versioning

on:
  push:
    branches: [master]

jobs:
  version_bump: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2    
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits)}}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          MESSAGES_JOINED: ${{ toJson(join(github.event.commits.*.message)) }}
          MESSAGES_TEST: ${{ contains(join(github.event.commits.*.message),'#skip') }}          
        run: echo "$COMMIT_MESSAGES $MESSAGES_JOINED $MESSAGES_TEST"