name: Versioning

on:
  push:
    branches: [master]

jobs:
  version_bump: 
    runs-on: ubuntu-18.04
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          WITH_V: true
          DEFAULT_BUMP: patch
